### ISSUE TITLE
Doesn't work, i tried this with stylus and don't work even with Rehike

### ISSUE THREAD

**Issue by goodoldweb2013** [Yaasir-AS/YouTube-2012-to-2014-Theme#1]

**Comment by Yaasir-AS** [comment]
Could you elaborate? It could have something to do with how the style works, or the browser you are using. It's working on my end

**Comment by Yaasir-AS** [comment]
By the way, did you install it properly? You're supposed to go to the usercss and click on raw to install it

**Comment by Yaasir-AS** [comment]
The user installed it the wrong way as I didn't specify how it was to be installed. The page has been updated to have a direct install link
